apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: microservice-project
  namespace: argocd
spec:
  description: 마이크로서비스 전용 프로젝트
  sourceRepos:
    - https://github.com/myorg/infrastructure-gitops
  destinations:
    - namespace: "*"
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
