apiVersion: apps/v1
kind: Deployment
metadata:
  name: community-service
  namespace: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: community-service
  template:
    metadata:
      labels:
        app: community-service
    spec:
      containers:
        - name: community-service
          image: kohyunchoel/befly-community:10a4237
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "1Gi"
              cpu: "800m"
          ports:
            - containerPort: 8083
      imagePullSecrets:
        - name: my-registry-secret
