apiVersion: v1
kind: Service
metadata:
  name: community-service
  namespace: backend
spec:
  selector:
    app: community-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8083
  type: ClusterIP