apiVersion: apps/v1
kind: Deployment
metadata:
  name: consult-service
  namespace: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: consult-service
  template:
    metadata:
      labels:
        app: consult-service
    spec:
      containers:
        - name: consult-service
          image: kohyunchoel/befly-ai:b0f4419
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "1Gi"
              cpu: "800m"
          ports:
            - containerPort: 8000
          envFrom:
            - secretRef:
                name: consult-service-secret
      imagePullSecrets:
        - name: my-registry-secret
