apiVersion: v1
kind: Service
metadata:
  name: consult-service
  namespace: backend
spec:
  selector:
    app: consult-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: ClusterIP