apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-service
  namespace: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gateway-service
  template:
    metadata:
      labels:
        app: gateway-service
    spec:
      containers:
        - name: gateway-service
          image: kohyunchoel/befly-gateway:7afab87
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "1Gi"
              cpu: "800m"
          ports:
            - containerPort: 8000
      imagePullSecrets:
        - name: my-registry-secret
